depends:
    - test-runner

source:
    - messagebus.c

tests:
    - tests/mocks/synchronization.cpp
    - tests/atomicity.cpp
    - tests/msgbus.cpp
    - tests/signaling.cpp
    - tests/foreach.cpp

target.demo:
    - examples/posix/demo.c
    - examples/posix/port.c

target.demo_protobuf:
    - examples/protobuf/demo.c
    - examples/posix/port.c

target.benchmark:
    - examples/protobuf/benchmark.c
    - examples/posix/port.c


# FIXME if we want to ever mainline the Protobuf+msgbus pattern we should
# probably use "messages" instead of "target.messages"
target.messages:
  - examples/protobuf/simple.proto

target.arm:
    - examples/chibios/port.c

include_directories:
  - examples/protobuf/nanopb

templates:
    demo.jinja: CMakeLists.txt
